# Generated by Django 3.2.5 on 2021-10-09 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
